export const LAY_DANH_SACH_PHIM = "LAY_DANH_SACH_PHIM";
export const LAY_CHI_TIET_PHIM = "LAY_CHI_TIET_PHIM";
export const LAY_CHI_TIET_PHONG_VE = "LAY_CHI_TIET_PHONG_VE";
export const DANG_NHAP_NGUOI_DUNG = "DANG_NHAP_NGUOI_DUNG";
export const SET_USERLOGIN_FROM_STORAGE = "SET_USERLOGIN_FROM_STORAGE";
export const DANG_XUAT = "DANG_XUAT";
export const LAY_THONG_TIN_USER = "LAY_THONG_TIN_USER";
